### ISSUE TITLE
Adding progress information

### ISSUE THREAD

**Issue by Crabzmatic** [konstmish/opt_methods#2]
Have you considered adding some kind of progress information for optimizers? I think when `it_max` is set, a `tqdm` progress bar would be very helpful and reasonable.

I think it would suffice to add something like this:
`for it in tqdm(range(self.it_max))`
besides this:
`while not self.check_convergence():`

Does this sound reasonable?

**Comment by konstmish** [comment]
Thanks for the suggestion, I can indeed add a basic implementation of tqdm and then maybe put a message if the optimizer interrupts early. I will update it next week

**Comment by konstmish** [comment]
I've added tqdm
